### ISSUE TITLE
Azure Automation: Automatically publish modules to Automation account and Hybrid Runbook Worker

### ISSUE THREAD

**Issue by janegilring** [CrayonAS/AutomationEasy#32]
**Summary of the new feature**

In the Azure DevOps release pipeline template, add support for automatically publish PowerShell modules to Automation accounts and Hybrid Runbook Workers.

One option could be using Azure DevOps as a PowerShellGet repository and run Update-Module on the Hybrid Runbook Worker.

**Comment by mortenlerudjordet** [comment]
Need more testing to see if any of the different scenarios has bugs.

**Comment by mortenlerudjordet** [comment]
Base functionality done.
