### ISSUE TITLE
Install VS TS Tasks for Azure Automation

### ISSUE THREAD

**Issue by janegilring** [CrayonAS/AutomationEasy#36]
**Summary of the new feature**

Install VS TS Tasks for Azure Automation in Azure DevOps
https://github.com/azureautomation/vststasks

**Comment by mortenlerudjordet** [comment]
Har lagt det opp for import men har ikke rettigheter for å få lov mot Azure DevOps er bare @tomlarse som har denne org tilgangen.

**Comment by mortenlerudjordet** [comment]
Fikk rettigheter, ferdig importert og tilgjengelig for org
