### ISSUE TITLE
Default repository for this project to dev

### ISSUE THREAD

**Issue by mortenlerudjordet** [CrayonAS/AutomationEasy#45]
I suggest we set Dev as the default repository for this  project as we are encouraging contributors to fork this and not master.

In my opinion this will alleviate some possible confusion.

**Comment by janegilring** [comment]
For contributors, I agree.
For others who just want to clone the repo, they might end up cloning the dev branch unintentionally.

Maybe we should consider adding a Zip-file under [Releases](https://github.com/PowerShell/Plaster/releases) ? That way, we can also strip away all of the content not relevant for non-devs.

If we do that - and update the download-instructions in the README & documentation, I see no issues changing default branch to dev.

**Comment by tomlarse** [comment]
This was one of the aspects we discussed when we were talking about releases and how it will get installed. The options we came up with were

 * `master` is the stable release and end users just `git clone` and then run `Invoke-Plaster`
 * Generate a zip file under releases at defined stable commits, end users download and run `Invoke-Plaster`

Both of these are acceptable to me, I lean slightly towards the second (publish release) option.

**Comment by mortenlerudjordet** [comment]
If the intention is to have all go through the github page, I then understand why we would prefer that master is the default.

**Comment by tomlarse** [comment]
Yup, it was just an arbitrary decision. Switching to the release feature makes a compelling use case for a release pipeline as well :)

**Comment by mortenlerudjordet** [comment]
I'll close this as agreement has been had.
