### ISSUE TITLE
Typo in New-AzureLogAnalyticsWorkspace.ps1

### ISSUE THREAD

**Issue by endreigesund** [CrayonAS/AutomationEasy#64]
fails to create Resource group.

Parameter $ResourceGroupName isn't used when creating. Wrong variablename in code:
try {

    Get-AzResourceGroup -Name $ResourceGroup -ErrorAction Stop

} catch {

    New-AzResourceGroup -Name $ResourceGroup -Location $Location

}

![image](https://user-images.githubusercontent.com/22214517/55160169-02142e80-5163-11e9-91dd-9995172bdde2.png)

**Comment by janegilring** [comment]
Fixed by https://github.com/CrayonAS/AutomationEasy/pull/65
